In [84]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('../data/netflix_customer_churn.csv')
df.head()

,customer_id,age,gender,subscription_type,watch_hours,last_login_days,region,device,monthly_fee,churned,payment_method,number_of_profiles,avg_watch_time_per_day,favorite_genre
0,a9b75100-82a8-427a-a208-72f24052884a,51,Other,Basic,14.73,29,Africa,TV,8.99,1,Gift Card,1,0.49,Action
1,49a5dfd9-7e69-4022-a6ad-0a1b9767fb5b,47,Other,Standard,0.70,19,Europe,Mobile,13.99,1,Gift Card,5,0.03,Sci-Fi
2,4d71f6ce-fca9-4ff7-8afa-197ac24de14b,27,Female,Standard,16.32,10,Asia,TV,13.99,0,Crypto,2,1.48,Drama
3,d3c72c38-631b-4f9e-8a0e-de103cad1a7d,53,Other,Premium,4.51,12,Oceania,TV,17.99,1,Crypto,2,0.35,Horror
4,4e265c34-103a-4dbb-9553-76c9aa47e946,56,Other,Standard,1.89,13,Africa,Mobile,13.99,1,Crypto,2,0.13,Action

In [85]:
# Checking data

print("\nData types:")
print(df.dtypes)

print("\nMissing values:")
print(df.isnull().sum())

Data types:
customer_id                   str
age                         int64
gender                        str
subscription_type             str
watch_hours               float64
last_login_days             int64
region                        str
device                        str
monthly_fee               float64
churned                     int64
payment_method                str
number_of_profiles          int64
avg_watch_time_per_day    float64
favorite_genre                str
dtype: object

Missing values:
customer_id               0
age                       0
gender                    0
subscription_type         0
watch_hours               0
last_login_days           0
region                    0
device                    0
monthly_fee               0
churned                   0
payment_method            0
number_of_profiles        0
avg_watch_time_per_day    0
favorite_genre            0
dtype: int64

In [86]:
#Does subscription type affect churn?
df.groupby('subscription_type')['churned'].mean() * 100

subscription_type
Basic       61.830223
Premium     43.709392
Standard    45.443499
Name: churned, dtype: float64

In [87]:
#Does age differ between subscription types?
df.groupby('subscription_type')['age'].mean()

subscription_type
Basic       44.223359
Premium     43.719433
Standard    43.599635
Name: age, dtype: float64

In [88]:
#Do churned users watch less and log in less often?
df.groupby('churned')[['watch_hours', 'last_login_days', 'monthly_fee']].mean()

         watch_hours  last_login_days  monthly_fee
churned
0          17.449590        21.771026    14.248350
1           5.918497        38.309344    13.125189

In [89]:
print("Key findings:")
print("1. Basic plan churn rate: 61.8%")
print("2. Churned users last logged in 38 days ago vs 22 days for active users")
print("3. Churned users watch fewer hours: 15.9 vs 17.4")

Key findings:
1. Basic plan churn rate: 61.8%
2. Churned users last logged in 38 days ago vs 22 days for active users
3. Churned users watch fewer hours: 15.9 vs 17.4